import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { createClient } from "@libsql/client";

const databaseUrl = process.env.DB_FILE_NAME ?? "file:./data/cc-offers.sqlite";
const outputFile =
  process.env.DEXIE_SEED_FILE ?? "src/data/credit-card-offers.seed.ts";

const client = createClient({ url: databaseUrl });

type JsonValue = null | string | number | boolean | JsonValue[] | JsonObject;
type JsonObject = { [key: string]: JsonValue };

type SqliteValue = null | string | number | bigint | Uint8Array;

interface ColumnInfo {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: SqliteValue;
  pk: number;
}

function normalizeValue(value: SqliteValue): JsonValue {
  if (typeof value === "bigint") {
    return Number(value);
  }

  if (value instanceof Uint8Array) {
    return Buffer.from(value).toString("base64");
  }

  return value;
}

function sqlColumnToTsField(column: ColumnInfo): string {
  const type = column.type.toLowerCase().includes("integer") ? "number" : "string";
  const nullable = column.notnull !== 1 && column.pk !== 1;

  return `  ${column.name}: ${type}${nullable ? " | null" : ""};`;
}

function createSeedFile(columns: ColumnInfo[], rows: JsonObject[]): string {
  const generatedAt = new Date().toISOString();
  const typeFields = columns
    .map((column) => sqlColumnToTsField(column))
    .join("\n");
  const serializedRows = JSON.stringify(rows, null, 2);

  return `import type Dexie from "dexie";

// Generated by scripts/export-sqlite-for-dexie.ts from ${databaseUrl}
// Generated at ${generatedAt}
// Do not edit this file by hand. Re-run \`npm run dexie:export\` instead.

export const CREDIT_CARD_OFFERS_STORE = "creditCardOffers" as const;
export const CREDIT_CARD_OFFERS_DEXIE_SCHEMA =
  "id, issuer, category, retrieved" as const;

export interface CreditCardOfferSeed {
${typeFields}
}

export const CREDIT_CARD_OFFERS_SEED = ${serializedRows} as const satisfies readonly CreditCardOfferSeed[];

export async function seedCreditCardOffers(db: Dexie): Promise<void> {
  await db
    .table(CREDIT_CARD_OFFERS_STORE)
    .bulkPut(CREDIT_CARD_OFFERS_SEED as readonly CreditCardOfferSeed[]);
}
`;
}

async function main(): Promise<void> {
  const tableInfo = await client.execute("pragma table_info(credit_card_offers)");
  const tableColumns = tableInfo.rows.map((row) => ({
    cid: Number(row.cid),
    name: String(row.name),
    type: String(row.type),
    notnull: Number(row.notnull),
    dflt_value: row.dflt_value as SqliteValue,
    pk: Number(row.pk),
  }));
  const result = await client.execute("select * from credit_card_offers order by id");
  const columns = tableColumns.map((column) => column.name);
  const rows = result.rows.map((row) => {
    return Object.fromEntries(
      columns.map((column, index) => [
        column,
        normalizeValue(
          (Object.hasOwn(row, column)
            ? row[column]
            : row[index as keyof typeof row]) as SqliteValue,
        ),
      ]),
    );
  });

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, createSeedFile(tableColumns, rows), "utf8");

  console.log(
    `Exported ${rows.length} credit_card_offers rows to ${outputFile}`,
  );
}

try {
  await main();
} finally {
  client.close();
}
